export default [
  {
    title: 'LIVE A LIVE',
    topLevelFilters: [],
    nsoFeatures: null,
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Pre-order', 'Coming soon'],
    genres: ['Role-Playing'],
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 49.99,
      salePrice: null,
      finalPrice: 49.99,
    },
    priceRange: '$40+',
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    collectionPriceRange: '$40 - $59.99',
    esrbRating: 'RP',
    esrbDescriptors: ['May contain content inappropriate for children. Visit www.esrb.org for rating information.'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: null,
    classindDescriptors: null,
    playerCount: 'Single Player',
    productImage: 'ncom/en_US/games/switch/l/live-a-live-switch/hero',
    softwareDeveloper: 'SQUARE ENIX',
    softwarePublisher: 'Nintendo',
    description:
      'Previously unreleased outside of Japan, the RPG game LIVE A LIVE is releasing on the Nintendo Switch system in the HD-2D style! Seven different stories featuring different protagonists, time periods, and gameplay styles await. In The Wild West, a wandere…',
    sku: '7100050787',
    nsuid: '70010000050787',
    releaseDateDisplay: null,
    urlKey: 'live-a-live-switch',
    url: '/store/products/live-a-live-switch/',
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100050787',
    _highlightResult: {
      description: {
        value:
          'Previously unreleased outside of Japan, the RPG game LIVE A LIVE is releasing on the Nintendo Switch system in the HD-2D style! Seven different stories featuring different protagonists, time periods, and gameplay styles await. In The Wild West, a wandere…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    availability: ['Pre-order', 'Coming soon'],
    classindDescriptors: null,
    classindRating: null,
    collectionPriceRange: '$40 - $59.99',
    corePlatforms: ['Nintendo Switch'],
    createdAt: '2022-02-11T23:46:40.000Z',
    demoNsuid: null,
    description:
      'Edelgard, Dimitri, Claude, and other Fire Emblem: Three Houses characters return to put their combat expertise on display as you revisit a war-torn Fódlan. Unleash devastating combos and striking special moves in action-packed, real-time combat Cut throu…',
    editions: ['Digital'],
    esrbDescriptors: ['Violence', 'Mild Suggestive Themes', 'Alcohol Reference'],
    esrbRating: 'T',
    exclusive: false,
    featuredProduct: true,
    franchises: ['Fire Emblem'],
    genres: ['Action', 'Strategy', 'Role-Playing', 'Simulation'],
    nsoFeatures: ['Save Data Cloud'],
    nsuid: '70010000050778',
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    platinumPoints: null,
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    playerCount: '2+',
    price: {
      regPrice: 59.99,
      salePrice: null,
      finalPrice: 59.99,
    },
    priceRange: '$40+',
    productImage: 'ncom/en_US/games/switch/f/fire-emblem-warriors-three-hopes-switch/hero',
    releaseDateDisplay: null,
    sku: '7100050778',
    smecDescriptors: null,
    smecRating: null,
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    title: 'Fire Emblem Warriors: Three Hopes',
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    topLevelFilters: [],
    updatedAt: '2022-03-03T16:52:23.000Z',
    url: '/store/products/fire-emblem-warriors-three-hopes-switch/',
    urlKey: 'fire-emblem-warriors-three-hopes-switch',
    visibleInSearch: true,
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100050778',
    _highlightResult: {
      description: {
        value:
          'Edelgard, Dimitri, Claude, and other Fire Emblem: Three Houses characters return to put their combat expertise on display as you revisit a war-torn Fódlan. Unleash devastating combos and striking special moves in action-packed, real-time combat Cut throu…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    availability: ['Pre-order', 'Coming soon'],
    classindDescriptors: ['Fantasy Violence'],
    classindRating: 'L',
    collectionPriceRange: '$40 - $59.99',
    corePlatforms: ['Nintendo Switch'],
    createdAt: '2022-02-11T23:46:32.000Z',
    demoNsuid: null,
    description:
      'Introducing Strike, a 5-on-5, soccer-like sport with no rules—do whatever it takes to win! Get gritty and try to score the most goals by tackling enemies, using items, and pulling off score-boosting special shots. Super Mario series mainstays like Peach,…',
    editions: ['Digital'],
    esrbDescriptors: ['Cartoon Violence', 'Comic Mischief'],
    esrbRating: 'E10',
    exclusive: false,
    featuredProduct: true,
    franchises: ['Super Mario', 'Mario', 'Toad', 'Yoshi'],
    genres: ['Sports'],
    nsoFeatures: ['Online Play', 'Save Data Cloud'],
    nsuid: '70010000049936',
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    platinumPoints: null,
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    playerCount: '4+',
    price: {
      regPrice: 59.99,
      salePrice: null,
      finalPrice: 59.99,
    },
    priceRange: '$40+',
    productImage: 'ncom/en_US/games/switch/m/mario-strikers-battle-league-switch/hero',
    releaseDateDisplay: null,
    sku: '7100049936',
    smecDescriptors: null,
    smecRating: null,
    softwareDeveloper: 'Nintendo',
    softwarePublisher: 'Nintendo',
    title: 'Mario Strikers™: Battle League',
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    topLevelFilters: [],
    updatedAt: '2022-03-10T19:24:08.000Z',
    url: '/store/products/mario-strikers-battle-league-switch/',
    urlKey: 'mario-strikers-battle-league-switch',
    visibleInSearch: true,
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100049936',
    _highlightResult: {
      description: {
        value:
          'Introducing Strike, a 5-on-5, soccer-like sport with no rules—do whatever it takes to win! Get gritty and try to score the most goals by tackling enemies, using items, and pulling off score-boosting special shots. Super Mario series mainstays like Peach,…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    availability: ['Pre-order', 'Coming soon'],
    classindDescriptors: ['Violence'],
    classindRating: 'E',
    collectionPriceRange: '$20 - $39.99',
    corePlatforms: ['Nintendo Switch'],
    createdAt: '2022-02-11T23:46:56.000Z',
    demoNsuid: null,
    description:
      'Get moving* with Soccer, Volleyball, Bowling, Tennis, Badminton, and Chambara (Swordplay) using Joy-Con™ controllers! Controls are intuitive, so you can hit the court (or lanes, or field, or arena) and get started. With controlled motions you can curve y…',
    editions: ['Digital'],
    esrbDescriptors: ['Mild Violence'],
    esrbRating: 'E10',
    exclusive: false,
    featuredProduct: true,
    franchises: [],
    genres: ['Sports', 'Multiplayer', 'Party'],
    nsoFeatures: ['Online Play', 'Save Data Cloud'],
    nsuid: '70010000049931',
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    platinumPoints: null,
    playModes: ['TV mode', 'Tabletop mode'],
    playerCount: '4+',
    price: {
      regPrice: 39.99,
      salePrice: null,
      finalPrice: 39.99,
    },
    priceRange: '$20 - $39.99',
    productImage: 'ncom/en_US/games/switch/n/nintendo-switch-sports-switch/hero',
    releaseDateDisplay: null,
    sku: '7100049931',
    smecDescriptors: null,
    smecRating: null,
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    title: 'Nintendo Switch™ Sports',
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    topLevelFilters: [],
    updatedAt: '2022-02-28T21:53:44.000Z',
    url: '/store/products/nintendo-switch-sports-switch/',
    urlKey: 'nintendo-switch-sports-switch',
    visibleInSearch: true,
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100049931',
    _highlightResult: {
      description: {
        value:
          'Get moving* with Soccer, Volleyball, Bowling, Tennis, Badminton, and Chambara (Swordplay) using Joy-Con™ controllers! Controls are intuitive, so you can hit the court (or lanes, or field, or arena) and get started. With controlled motions you can curve y…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    availability: ['New releases', 'Available now'],
    classindDescriptors: ['There are no inadequacies'],
    classindRating: 'L',
    collectionPriceRange: '$40 - $59.99',
    corePlatforms: ['Nintendo Switch'],
    createdAt: '2022-01-24T19:08:19.000Z',
    demoNsuid: '70030000015727',
    description:
      'Float off on an all-new adventure as the powerful puffball, Kirby. Explore in 3D stages as you discover a mysterious world with abandoned structures from a past civilization—like a shopping mall?! Copy enemies’ abilities like the new Drill and Ranger and…',
    editions: ['Digital'],
    esrbDescriptors: ['Cartoon Violence'],
    esrbRating: 'E10',
    exclusive: false,
    featuredProduct: true,
    franchises: [],
    genres: ['Action', 'Platformer'],
    nsoFeatures: ['Online Play', 'Save Data Cloud'],
    nsuid: '70010000046405',
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    platinumPoints: null,
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    playerCount: '2+',
    price: {
      regPrice: 59.99,
      salePrice: null,
      finalPrice: 59.99,
    },
    priceRange: '$40+',
    productImage: 'ncom/en_US/games/switch/k/kirby-and-the-forgotten-land-switch/hero',
    releaseDateDisplay: null,
    sku: '7100046405',
    smecDescriptors: null,
    smecRating: null,
    softwareDeveloper: 'HAL Laboratory',
    softwarePublisher: 'Nintendo',
    title: 'Kirby™ and the Forgotten Land',
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    topLevelFilters: ['Demo Available'],
    updatedAt: '2022-03-14T18:56:24.000Z',
    url: '/store/products/kirby-and-the-forgotten-land-switch/',
    urlKey: 'kirby-and-the-forgotten-land-switch',
    visibleInSearch: true,
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100046405',
    _highlightResult: {
      description: {
        value:
          'Float off on an all-new adventure as the powerful puffball, Kirby. Explore in 3D stages as you discover a mysterious world with abandoned structures from a past civilization—like a shopping mall?! Copy enemies’ abilities like the new Drill and Ranger and…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    availability: ['Available now'],
    classindDescriptors: null,
    classindRating: 'L',
    collectionPriceRange: '$20 - $39.99',
    corePlatforms: ['Nintendo Switch'],
    createdAt: '2022-02-11T21:34:47.000Z',
    demoNsuid: null,
    description:
      'Racers who have an active Nintendo Switch Online + Expansion Pack membership will have access to all of these newly-added courses as they are released at no additional cost. Non-members can access the courses as they are released by purchasing the Mario …',
    editions: ['Digital'],
    esrbDescriptors: ['Comic Mischief'],
    esrbRating: 'E',
    exclusive: false,
    featuredProduct: true,
    franchises: [],
    genres: ['Multiplayer', 'Other', 'Racing'],
    nsoFeatures: null,
    nsuid: '70070000013723',
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    platinumPoints: null,
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    playerCount: null,
    price: {
      regPrice: 24.99,
      salePrice: null,
      finalPrice: 24.99,
    },
    priceRange: '$20 - $39.99',
    productImage:
      'ncom/en_US/dlc/switch-dlc/mario-kart-8-deluxe-dlc/bundles/mario-kart-8-deluxe-booster-course-pass/image',
    releaseDateDisplay: null,
    sku: '7700013723',
    smecDescriptors: null,
    smecRating: null,
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    title: 'Mario Kart™ 8 Deluxe – Booster Course Pass ',
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    topLevelFilters: ['Games with DLC'],
    updatedAt: '2022-03-28T20:55:31.000Z',
    url: '/store/products/mario-kart-8-deluxe-booster-course-pass-70070000013723-switch/',
    urlKey: 'mario-kart-8-deluxe-booster-course-pass-70070000013723-switch',
    visibleInSearch: true,
    type: 'game',
    dlcType: 'Bundle',
    hasDlc: true,
    objectID: '7700013723',
    _highlightResult: {
      description: {
        value:
          'Racers who have an active Nintendo Switch Online + Expansion Pack membership will have access to all of these newly-added courses as they are released at no additional cost. Non-members can access the courses as they are released by purchasing the Mario …',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    availability: ['Available now'],
    classindDescriptors: ['Violence', 'Legal Drugs', 'Sexual Content'],
    classindRating: 'E10',
    collectionPriceRange: '$40 - $59.99',
    corePlatforms: ['Nintendo Switch'],
    createdAt: '2021-11-12T20:49:31.000Z',
    demoNsuid: '70030000015524',
    description:
      'Command a group of warriors as Serenoa, heir of House Wolffort, in a tangled plot where your decisions make all the difference. Key choices you make will influence the story and outcome of this grand conflict. When faced with truly momentous decisions, y…',
    editions: ['Digital'],
    esrbDescriptors: ['Blood', 'Use of Alcohol', 'Mild Suggestive Themes', 'Language', 'Fantasy Violence'],
    esrbRating: 'T',
    exclusive: false,
    featuredProduct: true,
    franchises: [],
    genres: ['Role-Playing', 'Strategy', 'Adventure'],
    nsoFeatures: ['Save Data Cloud'],
    nsuid: '70010000046322',
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    platinumPoints: null,
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    playerCount: 'Single Player',
    price: {
      regPrice: 59.99,
      salePrice: null,
      finalPrice: 59.99,
    },
    priceRange: '$40+',
    productImage: 'ncom/en_US/games/switch/t/triangle-strategy-switch/hero',
    releaseDateDisplay: null,
    sku: '7100046322',
    smecDescriptors: null,
    smecRating: null,
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    title: 'TRIANGLE STRATEGY™',
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    topLevelFilters: ['Demo Available'],
    updatedAt: '2022-03-01T22:50:52.000Z',
    url: '/store/products/triangle-strategy-switch/',
    urlKey: 'triangle-strategy-switch',
    visibleInSearch: true,
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100046322',
    _highlightResult: {
      description: {
        value:
          'Command a group of warriors as Serenoa, heir of House Wolffort, in a tangled plot where your decisions make all the difference. Key choices you make will influence the story and outcome of this grand conflict. When faced with truly momentous decisions, y…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    availability: ['Available now'],
    classindDescriptors: ['Fantasy Violence'],
    classindRating: 'L',
    collectionPriceRange: '$40 - $59.99',
    corePlatforms: ['Nintendo Switch'],
    createdAt: '2021-11-12T20:59:18.000Z',
    demoNsuid: null,
    description:
      'Get ready for a new kind of grand, Pokémon adventure in Pokémon™ Legends: Arceus, a brand-new game from Game Freak that blends action and exploration with the RPG roots of the Pokémon series. Embark on survey missions in the ancient Hisui region. Explore…',
    editions: ['Digital'],
    esrbDescriptors: ['Mild Fantasy Violence'],
    esrbRating: 'E',
    exclusive: false,
    featuredProduct: true,
    franchises: ['Pokémon'],
    genres: ['Action', 'Role-Playing'],
    nsoFeatures: ['Online Play'],
    nsuid: '70010000039945',
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    platinumPoints: null,
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    playerCount: 'Single Player',
    price: {
      regPrice: 59.99,
      salePrice: null,
      finalPrice: 59.99,
    },
    priceRange: '$40+',
    productImage: 'ncom/en_US/games/switch/p/pokemon-legends-arceus-switch/hero',
    releaseDateDisplay: null,
    sku: '7100039945',
    smecDescriptors: null,
    smecRating: null,
    softwareDeveloper: 'GAME FREAK',
    softwarePublisher: 'Nintendo',
    title: 'Pokémon™ Legends: Arceus',
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    topLevelFilters: [],
    updatedAt: '2022-03-25T04:09:23.000Z',
    url: '/store/products/pokemon-legends-arceus-switch/',
    urlKey: 'pokemon-legends-arceus-switch',
    visibleInSearch: true,
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100039945',
    _highlightResult: {
      description: {
        value:
          'Get ready for a new kind of grand, Pokémon adventure in Pokémon™ Legends: Arceus, a brand-new game from Game Freak that blends action and exploration with the RPG roots of the Pokémon series. Embark on survey missions in the ancient Hisui region. Explore…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Bayonetta™ and Bayonetta™ 2 Digital Bundle',
    topLevelFilters: ['Games with DLC'],
    nsoFeatures: null,
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: null,
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 59.98,
      salePrice: null,
      finalPrice: 59.98,
    },
    priceRange: '$40+',
    playModes: ['Handheld mode', 'Tabletop mode', 'TV mode'],
    collectionPriceRange: '$40 - $59.99',
    esrbRating: 'M',
    esrbDescriptors: ['Blood and Gore', 'Suggestive Themes', 'Strong Language', 'Partial Nudity', 'Intense Violence'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E16',
    classindDescriptors: ['Sexual Content', 'Violence', 'Legal Drugs'],
    playerCount: null,
    productImage: 'ncom/en_US/dlc/switch-dlc/bayonetta-dlc/rom-bundle/bayonetta-and-bayonetta-2-digital-bundle/image',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'Strap on your heels (and the attached guns) in two nonstop action games. Use your witchy powers to conquer both heaven and hell in the critically-acclaimed Bayonetta and Bayonetta 2 games.  Meet the baddest witch around—Bayonetta Originally released in 2…',
    sku: '7700013538',
    nsuid: '70070000013538',
    releaseDateDisplay: null,
    urlKey: 'bayonetta-and-bayonetta-2-digital-bundle-switch',
    url: '/store/products/bayonetta-and-bayonetta-2-digital-bundle-switch/',
    type: 'game',
    dlcType: 'ROM Bundle',
    hasDlc: true,
    objectID: '7700013538',
    _highlightResult: {
      description: {
        value:
          'Strap on your heels (and the attached guns) in two nonstop action games. Use your witchy powers to conquer both heaven and hell in the critically-acclaimed Bayonetta and Bayonetta 2 games.  Meet the baddest witch around—Bayonetta Originally released in 2…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Big Brain Academy™: Brain vs. Brain',
    topLevelFilters: ['Demo Available'],
    nsoFeatures: ['Online Play', 'Save Data Cloud'],
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: ['Party', 'Puzzle'],
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: '70030000015040',
    platinumPoints: null,
    price: {
      regPrice: 29.99,
      salePrice: null,
      finalPrice: 29.99,
    },
    priceRange: '$20 - $39.99',
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    collectionPriceRange: '$20 - $39.99',
    esrbRating: 'E',
    esrbDescriptors: ['Mild Cartoon Violence'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E',
    classindDescriptors: null,
    playerCount: '4+',
    productImage: 'ncom/en_US/games/switch/b/big-brain-academy-brain-vs-brain-switch/hero',
    softwareDeveloper: 'Nintendo',
    softwarePublisher: 'Nintendo',
    description:
      'Take on a series of brain-bending activities that test your mental mettle in Big Brain Academy™: Brain vs. Brain for the Nintendo Switch™ system! Play a wide variety of activities, like memorizing a series of numbers, identifying an animal as it slowly c…',
    sku: '7100044951',
    nsuid: '70010000044951',
    releaseDateDisplay: null,
    urlKey: 'big-brain-academy-brain-vs-brain-switch',
    url: '/store/products/big-brain-academy-brain-vs-brain-switch/',
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100044951',
    _highlightResult: {
      description: {
        value:
          'Take on a series of brain-bending activities that test your mental mettle in Big Brain Academy™: Brain vs. Brain for the Nintendo Switch™ system! Play a wide variety of activities, like memorizing a series of numbers, identifying an animal as it slowly c…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    availability: ['Available now'],
    classindDescriptors: null,
    classindRating: 'L',
    collectionPriceRange: '$40 - $59.99',
    corePlatforms: ['Nintendo Switch'],
    createdAt: '2021-11-12T21:28:05.000Z',
    demoNsuid: null,
    description:
      'Experience the nostalgic story from the Pokémon™ Pearl Version game in a reimagined adventure, Pokémon Shining Pearl, now on the Nintendo Switch™ system! Adventures in the Pokémon Shining Pearl game will take place in the familiar Sinnoh region. Rich in …',
    editions: ['Digital'],
    esrbDescriptors: ['Mild Cartoon Violence'],
    esrbRating: 'E',
    exclusive: false,
    featuredProduct: true,
    franchises: ['Pokémon'],
    genres: ['Adventure', 'Role-Playing'],
    nsoFeatures: ['Online Play'],
    nsuid: '70010000039955',
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    platinumPoints: null,
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    playerCount: 'Single Player',
    price: {
      regPrice: 59.99,
      salePrice: null,
      finalPrice: 59.99,
    },
    priceRange: '$40+',
    productImage: 'ncom/en_US/games/switch/p/pokemon-shining-pearl-switch/hero',
    releaseDateDisplay: null,
    sku: '7100039955',
    smecDescriptors: null,
    smecRating: null,
    softwareDeveloper: 'ILCA',
    softwarePublisher: 'Nintendo',
    title: 'Pokémon™ Shining Pearl',
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    topLevelFilters: [],
    updatedAt: '2022-03-18T19:21:20.000Z',
    url: '/store/products/pokemon-shining-pearl-switch/',
    urlKey: 'pokemon-shining-pearl-switch',
    visibleInSearch: true,
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100039955',
    _highlightResult: {
      description: {
        value:
          'Experience the nostalgic story from the Pokémon™ Pearl Version game in a reimagined adventure, Pokémon Shining Pearl, now on the Nintendo Switch™ system! Adventures in the Pokémon Shining Pearl game will take place in the familiar Sinnoh region. Rich in …',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    availability: ['Available now'],
    classindDescriptors: null,
    classindRating: 'L',
    collectionPriceRange: '$40 - $59.99',
    corePlatforms: ['Nintendo Switch'],
    createdAt: '2021-11-12T21:22:14.000Z',
    demoNsuid: null,
    description:
      'Experience the nostalgic story from the Pokémon™ Diamond Version game in a reimagined adventure, Pokémon Brilliant Diamond, now on the Nintendo Switch™ system! Adventures in the Pokémon Brilliant Diamond game will take place in the familiar Sinnoh region…',
    editions: ['Digital'],
    esrbDescriptors: ['Mild Cartoon Violence'],
    esrbRating: 'E',
    exclusive: false,
    featuredProduct: true,
    franchises: ['Pokémon'],
    genres: ['Adventure', 'Role-Playing'],
    nsoFeatures: ['Online Play'],
    nsuid: '70010000039950',
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    platinumPoints: null,
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    playerCount: 'Single Player',
    price: {
      regPrice: 59.99,
      salePrice: null,
      finalPrice: 59.99,
    },
    priceRange: '$40+',
    productImage: 'ncom/en_US/games/switch/p/pokemon-brilliant-diamond-switch/hero',
    releaseDateDisplay: null,
    sku: '7100039950',
    smecDescriptors: null,
    smecRating: null,
    softwareDeveloper: 'ILCA',
    softwarePublisher: 'Nintendo',
    title: 'Pokémon™ Brilliant Diamond',
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    topLevelFilters: [],
    updatedAt: '2022-03-18T19:19:36.000Z',
    url: '/store/products/pokemon-brilliant-diamond-switch/',
    urlKey: 'pokemon-brilliant-diamond-switch',
    visibleInSearch: true,
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100039950',
    _highlightResult: {
      description: {
        value:
          'Experience the nostalgic story from the Pokémon™ Diamond Version game in a reimagined adventure, Pokémon Brilliant Diamond, now on the Nintendo Switch™ system! Adventures in the Pokémon Brilliant Diamond game will take place in the familiar Sinnoh region…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Pokémon™ Brilliant Diamond and Pokémon™ Shining Pearl Double Pack',
    topLevelFilters: [],
    nsoFeatures: ['Online Play'],
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: [],
    genres: ['Adventure', 'Role-Playing'],
    editions: ['Physical'],
    featuredProduct: true,
    franchises: ['Pokémon'],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 119.98,
      salePrice: null,
      finalPrice: 119.98,
    },
    priceRange: '$40+',
    playModes: ['Handheld mode', 'Tabletop mode', 'TV mode'],
    collectionPriceRange: '$60+',
    esrbRating: 'E',
    esrbDescriptors: ['Mild Cartoon Violence'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E',
    classindDescriptors: null,
    playerCount: 'Single Player',
    productImage:
      'ncom/en_US/products/games/switch/pokemon-brilliant-diamond-pokemon-shining-pearl-double-pack/switch-pokemon-brilliant-diamond-shining-pearl-2000x2000',
    softwareDeveloper: 'ILCA',
    softwarePublisher: 'Nintendo',
    description: null,
    sku: '114521',
    nsuid: null,
    releaseDateDisplay: null,
    urlKey: 'pokemon-brilliant-diamond-pokemon-shining-pearl-double-pack',
    url: '/store/products/pokemon-brilliant-diamond-pokemon-shining-pearl-double-pack/',
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '114521',
  },
  {
    availability: ['Available now'],
    classindDescriptors: null,
    classindRating: 'L',
    collectionPriceRange: '$60+',
    corePlatforms: ['Nintendo Switch'],
    createdAt: '2021-11-12T23:55:01.000Z',
    demoNsuid: null,
    description:
      'A double pack containing the Pokémon Brilliant Diamond and Pokémon Shining Pearl games are also available for purchase as a packaged version or as a digital downloadable version. The packaged version includes 1 physical Pokémon Brilliant Diamond game and…',
    editions: ['Digital'],
    esrbDescriptors: ['Mild Cartoon Violence'],
    esrbRating: 'E',
    exclusive: false,
    featuredProduct: true,
    franchises: [],
    genres: ['Adventure', 'Role-Playing'],
    nsoFeatures: null,
    nsuid: '70070000012398',
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    platinumPoints: null,
    playModes: null,
    playerCount: 'Single Player',
    price: {
      regPrice: 119.99,
      salePrice: null,
      finalPrice: 119.99,
    },
    priceRange: '$40+',
    productImage:
      'ncom/en_US/dlc/switch-dlc/pokemon-shining-pearl-dlc/rom-bundle/pokemon-brilliant-diamond-and-pokemon-shining-pearl-double-pack/image',
    releaseDateDisplay: null,
    sku: '7700012398',
    smecDescriptors: null,
    smecRating: null,
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    title: 'Pokémon™ Brilliant Diamond and Pokémon™ Shining Pearl Double Pack',
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    topLevelFilters: ['Games with DLC'],
    updatedAt: '2022-03-18T19:23:29.000Z',
    url: '/store/products/pokemon-brilliant-diamond-and-pokemon-shining-pearl-double-pack-switch/',
    urlKey: 'pokemon-brilliant-diamond-and-pokemon-shining-pearl-double-pack-switch',
    visibleInSearch: true,
    type: 'game',
    dlcType: 'ROM Bundle',
    hasDlc: true,
    objectID: '7700012398',
    _highlightResult: {
      description: {
        value:
          'A double pack containing the Pokémon Brilliant Diamond and Pokémon Shining Pearl games are also available for purchase as a packaged version or as a digital downloadable version. The packaged version includes 1 physical Pokémon Brilliant Diamond game and…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Grand Theft Auto: The Trilogy – The Definitive Edition',
    topLevelFilters: [],
    nsoFeatures: null,
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: ['Action', 'Adventure'],
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 59.99,
      finalPrice: 59.99,
      salePrice: null,
    },
    priceRange: '$40+',
    playModes: null,
    collectionPriceRange: '$40 - $59.99',
    esrbRating: 'M',
    esrbDescriptors: ['Blood and Gore', 'Intense Violence', 'Sexual Content', 'Strong Language', 'Use of Drugs'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E18',
    classindDescriptors: ['Illegal Drugs', 'Sexual Content', 'Violence'],
    playerCount: null,
    productImage:
      'ncom/en_US/dlc/switch-dlc/grand-theft-auto-iii-the-definitive-edition-dlc/rom-bundle/grand-theft-auto-the-trilogy-the-definitive-edition/image',
    softwareDeveloper: null,
    softwarePublisher: 'ROCKSTAR GAMES',
    description:
      'Three iconic cities, three epic stories. Play the genre-defining classics of the original Grand Theft Auto Trilogy: Grand Theft Auto III, Grand Theft Auto: Vice City and Grand Theft Auto: San Andreas updated for a new generation, now with across-the-boar…',
    sku: '7700013113',
    nsuid: '70070000013113',
    releaseDateDisplay: null,
    urlKey: 'grand-theft-auto-the-trilogy-the-definitive-edition-switch',
    url: '/store/products/grand-theft-auto-the-trilogy-the-definitive-edition-switch/',
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7700013113',
    _highlightResult: {
      description: {
        value:
          'Three iconic cities, three epic stories. Play the genre-defining classics of the original Grand Theft Auto Trilogy: Grand Theft Auto III, Grand Theft Auto: Vice City and Grand Theft Auto: San Andreas updated for a new generation, now with across-the-boar…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Animal Crossing™: New Horizons - Happy Home Paradise',
    topLevelFilters: ['DLC'],
    nsoFeatures: null,
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: null,
    editions: ['Digital'],
    featuredProduct: true,
    franchises: ['Animal Crossing'],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 24.99,
      salePrice: null,
      finalPrice: 24.99,
    },
    priceRange: '$20 - $39.99',
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    collectionPriceRange: '$20 - $39.99',
    esrbRating: 'E',
    esrbDescriptors: ['Comic Mischief'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E',
    classindDescriptors: null,
    playerCount: null,
    productImage:
      'ncom/en_US/dlc/switch-dlc/animal-crossing-new-horizons-dlc/individual/animal-crossing-new-horizons-happy-home-paradise/image',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'Join Lottie’s Paradise Planning team and travel to a distant group of beautiful resort islands with a diverse set of landscapes. This time, you are in charge of inviting characters as clients and helping them live out their own dream vacations. Choose fr…',
    sku: '7500030669',
    nsuid: '70050000030669',
    releaseDateDisplay: null,
    urlKey: 'animal-crossing-new-horizons-happy-home-paradise-70050000030669-switch',
    url: '/store/products/animal-crossing-new-horizons-happy-home-paradise-70050000030669-switch/',
    type: 'game',
    dlcType: 'Individual',
    hasDlc: true,
    objectID: '7500030669',
    _highlightResult: {
      description: {
        value:
          'Join Lottie’s Paradise Planning team and travel to a distant group of beautiful resort islands with a diverse set of landscapes. This time, you are in charge of inviting characters as clients and helping them live out their own dream vacations. Choose fr…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Fitness Boxing 2: Instructor Tunes',
    topLevelFilters: ['DLC'],
    nsoFeatures: null,
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: null,
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 4.99,
      salePrice: null,
      finalPrice: 4.99,
    },
    priceRange: '$0 - $4.99',
    playModes: null,
    collectionPriceRange: '$0 - $9.99',
    esrbRating: 'E',
    esrbDescriptors: null,
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E',
    classindDescriptors: null,
    playerCount: null,
    productImage:
      'ncom/en_US/dlc/switch-dlc/fitness-boxing-2-rhythm-and-exercise-dlc/individual/fitness-boxing-2-instructor-tunes/image',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description: 'Fitness Boxing 2: Instructor Tunes ',
    sku: '7500031293',
    nsuid: '70050000031293',
    releaseDateDisplay: null,
    urlKey: 'fitness-boxing-2-instructor-tunes-70050000031293-switch',
    url: '/store/products/fitness-boxing-2-instructor-tunes-70050000031293-switch/',
    type: 'game',
    dlcType: 'Individual',
    hasDlc: true,
    objectID: '7500031293',
    _highlightResult: {
      description: {
        value: 'Fitness Boxing 2: Instructor Tunes ',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Mario Party™ Superstars',
    topLevelFilters: [],
    nsoFeatures: ['Online Play', 'Save Data Cloud'],
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: ['Party', 'Multiplayer'],
    editions: ['Digital'],
    featuredProduct: true,
    franchises: ['Super Mario', 'Mario'],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 59.99,
      salePrice: null,
      finalPrice: 59.99,
    },
    priceRange: '$40+',
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    collectionPriceRange: '$40 - $59.99',
    esrbRating: 'E',
    esrbDescriptors: ['Mild Cartoon Violence'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E',
    classindDescriptors: null,
    playerCount: '4+',
    productImage: 'ncom/en_US/games/switch/m/mario-party-superstars-switch/hero',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'Calling all superstars! The Mario Party™ series is back with 5 classic boards from the Nintendo 64 Mario Party games. Race to get the most stars (and sabotage your opponents) on boards like the stellar Space Land or the spooky Horror Land! Party at your …',
    sku: '7100042934',
    nsuid: '70010000042934',
    releaseDateDisplay: null,
    urlKey: 'mario-party-superstars-switch',
    url: '/store/products/mario-party-superstars-switch/',
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100042934',
    _highlightResult: {
      description: {
        value:
          'Calling all superstars! The Mario Party™ series is back with 5 classic boards from the Nintendo 64 Mario Party games. Race to get the most stars (and sabotage your opponents) on boards like the stellar Space Land or the spooky Horror Land! Party at your …',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'SEGA Genesis™ – Nintendo Switch Online',
    topLevelFilters: [],
    nsoFeatures: ['Online Play', 'Save Data Cloud'],
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: ['Other'],
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 0,
      salePrice: null,
      finalPrice: 0,
    },
    priceRange: 'Free to start',
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    collectionPriceRange: 'Free to start',
    esrbRating: 'T',
    esrbDescriptors: ['Blood', 'Violence'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E10',
    classindDescriptors: ['Sexual Content', 'Inappropriate Language', 'Violence'],
    playerCount: '2+',
    productImage: 'ncom/en_US/games/switch/s/sega-genesis-nintendo-switch-online-switch/hero',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'With a Nintendo Switch Online + Expansion Pack membership, access a collection of SEGA Genesis™ games that are great to play anytime, anywhere! You can play these classic games with added features, such as rewind to recover rings in Sonic the Hedgehog 2,…',
    sku: '7100046988',
    nsuid: '70010000046988',
    releaseDateDisplay: null,
    urlKey: 'sega-genesis-nintendo-switch-online-switch',
    url: '/store/products/sega-genesis-nintendo-switch-online-switch/',
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100046988',
    _highlightResult: {
      description: {
        value:
          'With a Nintendo Switch Online + Expansion Pack membership, access a collection of SEGA Genesis™ games that are great to play anytime, anywhere! You can play these classic games with added features, such as rewind to recover rings in Sonic the Hedgehog 2,…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Nintendo 64™ – Nintendo Switch Online  ',
    topLevelFilters: [],
    nsoFeatures: ['Online Play', 'Save Data Cloud'],
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: ['Other'],
    editions: ['Digital'],
    featuredProduct: true,
    franchises: ['The Legend of Zelda', 'Mario', 'Star Fox', 'Zelda'],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 0,
      salePrice: null,
      finalPrice: 0,
    },
    priceRange: 'Free to start',
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    collectionPriceRange: 'Free to start',
    esrbRating: 'T',
    esrbDescriptors: ['Blood', 'Violence'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E16',
    classindDescriptors: ['Inappropriate Language', 'Violence'],
    playerCount: '4+',
    productImage: 'ncom/en_US/games/switch/n/nintendo-64-nintendo-switch-online-switch/hero',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'With a Nintendo Switch Online + Expansion Pack membership, access a collection of Nintendo 64™ games that are great to play anytime, anywhere! For the first time ever, you can play these classic games online and use voice chat via the Nintendo Switch Onl…',
    sku: '7100046983',
    nsuid: '70010000046983',
    releaseDateDisplay: null,
    urlKey: 'nintendo-64-nintendo-switch-online-switch',
    url: '/store/products/nintendo-64-nintendo-switch-online-switch/',
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100046983',
    _highlightResult: {
      description: {
        value:
          'With a Nintendo Switch Online + Expansion Pack membership, access a collection of Nintendo 64™ games that are great to play anytime, anywhere! For the first time ever, you can play these classic games online and use voice chat via the Nintendo Switch Onl…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Super Smash Bros.™ Ultimate: Challenger Pack 11',
    topLevelFilters: ['DLC'],
    nsoFeatures: null,
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: null,
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 5.99,
      salePrice: null,
      finalPrice: 5.99,
    },
    priceRange: '$5 - $9.99',
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    collectionPriceRange: '$0 - $9.99',
    esrbRating: 'E10',
    esrbDescriptors: ['Cartoon Violence', 'Suggestive Themes', 'Comic Mischief'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E10',
    classindDescriptors: ['Violence'],
    playerCount: null,
    productImage:
      'ncom/en_US/dlc/switch-dlc/super-smash-bros-ultimate-dlc/individual/super-smash-bros-ultimate-challenger-pack-11/image',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'Sora from the KINGDOM HEARTS  series joins the Super Smash Bros. Ultimate roster! Wielding his Keyblade and an arsenal of spells, Sora is a veteran when it comes to battling enemies and is ready to bring his 3-hit combos and aerial style into the fray. T…',
    sku: '7500018966',
    nsuid: '70050000018966',
    releaseDateDisplay: null,
    urlKey: 'super-smash-bros-ultimate-challenger-pack-11-70050000018966-switch',
    url: '/store/products/super-smash-bros-ultimate-challenger-pack-11-70050000018966-switch/',
    type: 'game',
    dlcType: 'Individual',
    hasDlc: true,
    objectID: '7500018966',
    _highlightResult: {
      description: {
        value:
          'Sora from the KINGDOM HEARTS  series joins the Super Smash Bros. Ultimate roster! Wielding his Keyblade and an arsenal of spells, Sora is a veteran when it comes to battling enemies and is ready to bring his 3-hit combos and aerial style into the fray. T…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Spirit Booster Bundle #2 - Reaching Lv. MAX',
    topLevelFilters: ['DLC'],
    nsoFeatures: null,
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: null,
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 0,
      salePrice: null,
      finalPrice: 0,
    },
    priceRange: 'Free to start',
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    collectionPriceRange: 'Free to start',
    esrbRating: 'E10',
    esrbDescriptors: ['Cartoon Violence', 'Suggestive Themes', 'Comic Mischief'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E10',
    classindDescriptors: ['Violence'],
    playerCount: null,
    productImage:
      'ncom/en_US/dlc/switch-dlc/super-smash-bros-ultimate-dlc/individual/spirit-booster-bundle-2-reaching-lv-max/hero',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'This bonus content is an exclusive offer for those with an active Nintendo Switch Online membership. You will be able to download items, which can be used in Super Smash Bros. Ultimate, for free. The set contains the following: ・3000 SP ・Snack (L) x30',
    sku: '7500021151',
    nsuid: '70050000021151',
    releaseDateDisplay: null,
    urlKey: 'spirit-booster-bundle-2-reaching-lv-max-70050000021151-switch',
    url: '/store/products/spirit-booster-bundle-2-reaching-lv-max-70050000021151-switch/',
    type: 'game',
    dlcType: 'Individual',
    hasDlc: true,
    objectID: '7500021151',
    _highlightResult: {
      description: {
        value:
          'This bonus content is an exclusive offer for those with an active Nintendo Switch Online membership. You will be able to download items, which can be used in Super Smash Bros. Ultimate, for free. The set contains the following: ・3000 SP ・Snack (L) x30',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    availability: ['Available now'],
    classindDescriptors: ['Violence', 'Sexual Content'],
    classindRating: 'E10',
    collectionPriceRange: '$40 - $59.99',
    corePlatforms: ['Nintendo Switch'],
    createdAt: '2021-11-12T21:22:28.000Z',
    demoNsuid: '70030000014923',
    description:
      'For a limited time, you can earn DOUBLE My Nintendo Gold Points on Metroid Dread. That means you can earn 10% in Gold Points*—which you can then use toward your next eligible digital game or DLC. Join bounty hunter Samus Aran as she tries to escape a dea…',
    editions: ['Digital'],
    esrbDescriptors: ['Animated Blood', 'Fantasy Violence'],
    esrbRating: 'T',
    exclusive: false,
    featuredProduct: true,
    franchises: ['Metroid'],
    genres: ['Action', 'Adventure'],
    nsoFeatures: ['Save Data Cloud'],
    nsuid: '70010000042924',
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    platinumPoints: null,
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    playerCount: 'Single Player',
    price: {
      regPrice: 59.99,
      salePrice: null,
      finalPrice: 59.99,
    },
    priceRange: '$40+',
    productImage: 'ncom/en_US/games/switch/m/metroid-dread-switch/hero',
    releaseDateDisplay: null,
    sku: '7100042924',
    smecDescriptors: null,
    smecRating: null,
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    title: 'Metroid™ Dread',
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    topLevelFilters: ['Demo Available'],
    updatedAt: '2022-03-01T08:22:54.000Z',
    url: '/store/products/metroid-dread-switch/',
    urlKey: 'metroid-dread-switch',
    visibleInSearch: true,
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100042924',
    _highlightResult: {
      description: {
        value:
          'For a limited time, you can earn DOUBLE My Nintendo Gold Points on Metroid Dread. That means you can earn 10% in Gold Points*—which you can then use toward your next eligible digital game or DLC. Join bounty hunter Samus Aran as she tries to escape a dea…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'WarioWare™: Get It Together!',
    topLevelFilters: ['Demo Available'],
    nsoFeatures: ['Online Play', 'Save Data Cloud'],
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: ['Action', 'Party'],
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: '70030000014425',
    platinumPoints: null,
    price: {
      regPrice: 49.99,
      salePrice: null,
      finalPrice: 49.99,
    },
    priceRange: '$40+',
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    collectionPriceRange: '$40 - $59.99',
    esrbRating: 'E10',
    esrbDescriptors: ['Cartoon Violence', 'Crude Humor'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E',
    classindDescriptors: ['Fantasy Violence'],
    playerCount: '4+',
    productImage: 'ncom/en_US/games/switch/w/warioware-get-it-together-switch/hero',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'Take on over 200 quick and quirky microgames—solo or with friends*! What is a microgame? First, choose from a kooky crew of characters, each with their own distinct abilities. Then, short-and-sweet instructions will appear on screen. Finally, use your ch…',
    sku: '7100042929',
    nsuid: '70010000042929',
    releaseDateDisplay: null,
    urlKey: 'warioware-get-it-together-switch',
    url: '/store/products/warioware-get-it-together-switch/',
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100042929',
    _highlightResult: {
      description: {
        value:
          'Take on over 200 quick and quirky microgames—solo or with friends*! What is a microgame? First, choose from a kooky crew of characters, each with their own distinct abilities. Then, short-and-sweet instructions will appear on screen. Finally, use your ch…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    availability: ['Available now'],
    classindDescriptors: ['Violence'],
    classindRating: 'E10',
    collectionPriceRange: '$40 - $59.99',
    corePlatforms: ['Nintendo Switch'],
    createdAt: '2021-11-12T20:55:17.000Z',
    demoNsuid: null,
    description:
      'For a limited time, you can earn DOUBLE My Nintendo Gold Points on The Legend of Zelda: Skyward Sword HD. That means you can earn 10% in Gold Points*—which you can then use toward your next eligible digital game or DLC. Solve puzzles, explore dungeons, a…',
    editions: ['Digital'],
    esrbDescriptors: ['Comic Mischief', 'Fantasy Violence', 'Animated Blood'],
    esrbRating: 'E10',
    exclusive: false,
    featuredProduct: true,
    franchises: ['The Legend of Zelda', 'Link', 'Zelda'],
    genres: ['Adventure', 'Action'],
    nsoFeatures: ['Save Data Cloud'],
    nsuid: '70010000038612',
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    platinumPoints: null,
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    playerCount: 'Single Player',
    price: {
      regPrice: 59.99,
      salePrice: null,
      finalPrice: 59.99,
    },
    priceRange: '$40+',
    productImage: 'ncom/en_US/games/switch/t/the-legend-of-zelda-skyward-sword-hd-switch/hero',
    releaseDateDisplay: null,
    sku: '7100038612',
    smecDescriptors: null,
    smecRating: null,
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    title: 'The Legend of Zelda™: Skyward Sword HD',
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    topLevelFilters: [],
    updatedAt: '2022-03-01T08:17:41.000Z',
    url: '/store/products/the-legend-of-zelda-skyward-sword-hd-switch/',
    urlKey: 'the-legend-of-zelda-skyward-sword-hd-switch',
    visibleInSearch: true,
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100038612',
    _highlightResult: {
      description: {
        value:
          'For a limited time, you can earn DOUBLE My Nintendo Gold Points on The Legend of Zelda: Skyward Sword HD. That means you can earn 10% in Gold Points*—which you can then use toward your next eligible digital game or DLC. Solve puzzles, explore dungeons, a…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Fitness Boxing 2: Musical Journey',
    topLevelFilters: ['DLC'],
    nsoFeatures: null,
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: null,
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 4.99,
      salePrice: null,
      finalPrice: 4.99,
    },
    priceRange: '$0 - $4.99',
    playModes: ['TV mode', 'Tabletop mode'],
    collectionPriceRange: '$0 - $9.99',
    esrbRating: 'E',
    esrbDescriptors: null,
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E',
    classindDescriptors: null,
    playerCount: null,
    productImage:
      'ncom/en_US/dlc/switch-dlc/fitness-boxing-2-rhythm-and-exercise-dlc/individual/fitness-boxing-2-musical-journey/image',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'Take a workout journey with a 10-track pack of tunes created just for this game.  The Fitness Boxing 2: Musical Journey pack* includes 10 adventurous tunes that draw inspiration from around the globe.  You can expect a variety of tunes that include groov…',
    sku: '7500028907',
    nsuid: '70050000028907',
    releaseDateDisplay: null,
    urlKey: 'fitness-boxing-2-musical-journey-70050000028907-switch',
    url: '/store/products/fitness-boxing-2-musical-journey-70050000028907-switch/',
    type: 'game',
    dlcType: 'Individual',
    hasDlc: true,
    objectID: '7500028907',
    _highlightResult: {
      description: {
        value:
          'Take a workout journey with a 10-track pack of tunes created just for this game.  The Fitness Boxing 2: Musical Journey pack* includes 10 adventurous tunes that draw inspiration from around the globe.  You can expect a variety of tunes that include groov…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Super Smash Bros.™ Ultimate: Challenger Pack 10',
    topLevelFilters: ['DLC'],
    nsoFeatures: null,
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: null,
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 5.99,
      salePrice: null,
      finalPrice: 5.99,
    },
    priceRange: '$5 - $9.99',
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    collectionPriceRange: '$0 - $9.99',
    esrbRating: 'E10',
    esrbDescriptors: ['Cartoon Violence', 'Suggestive Themes', 'Comic Mischief'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E10',
    classindDescriptors: ['Violence'],
    playerCount: null,
    productImage:
      'ncom/en_US/dlc/switch-dlc/super-smash-bros-ultimate-dlc/individual/super-smash-bros-ultimate-challenger-pack-10/image',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'From the Tekken series, Kazuya Mishima brings his demonic DNA into the fray as a DLC fighter in the Super Smash Bros. Ultimate game. Kazuya’s fighting style captures the distinct style of the Tekken series as he gets up close and personal with heavy stri…',
    sku: '7500018965',
    nsuid: '70050000018965',
    releaseDateDisplay: null,
    urlKey: 'super-smash-bros-ultimate-challenger-pack-10-70050000018965-switch',
    url: '/store/products/super-smash-bros-ultimate-challenger-pack-10-70050000018965-switch/',
    type: 'game',
    dlcType: 'Individual',
    hasDlc: true,
    objectID: '7500018965',
    _highlightResult: {
      description: {
        value:
          'From the Tekken series, Kazuya Mishima brings his demonic DNA into the fray as a DLC fighter in the Super Smash Bros. Ultimate game. Kazuya’s fighting style captures the distinct style of the Tekken series as he gets up close and personal with heavy stri…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    availability: ['Available now'],
    classindDescriptors: ['Fantasy Violence'],
    classindRating: 'E',
    collectionPriceRange: '$40 - $59.99',
    corePlatforms: ['Nintendo Switch'],
    createdAt: '2021-11-12T20:32:14.000Z',
    demoNsuid: null,
    description:
      'For a limited time, you can earn DOUBLE My Nintendo Gold Points on Mario Golf: Super Rush. That means you can earn 10% in Gold Points*—which you can then use toward your next eligible digital game or DLC. Golf with a Mushroom Kingdom twist! Hit the green…',
    editions: ['Digital'],
    esrbDescriptors: ['Mild Cartoon Violence'],
    esrbRating: 'E',
    exclusive: false,
    featuredProduct: true,
    franchises: ['Super Mario', 'Mario', 'Yoshi'],
    genres: ['Sports', 'Multiplayer'],
    nsoFeatures: ['Online Play', 'Save Data Cloud'],
    nsuid: '70010000038622',
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    platinumPoints: null,
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    playerCount: '4+',
    price: {
      regPrice: 59.99,
      salePrice: null,
      finalPrice: 59.99,
    },
    priceRange: '$40+',
    productImage: 'ncom/en_US/games/switch/m/mario-golf-super-rush-switch/hero',
    releaseDateDisplay: null,
    sku: '7100038622',
    smecDescriptors: null,
    smecRating: null,
    softwareDeveloper: 'CAMELOT',
    softwarePublisher: 'Nintendo',
    title: 'Mario Golf™: Super Rush',
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    topLevelFilters: [],
    updatedAt: '2022-03-01T08:08:44.000Z',
    url: '/store/products/mario-golf-super-rush-switch/',
    urlKey: 'mario-golf-super-rush-switch',
    visibleInSearch: true,
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100038622',
    _highlightResult: {
      description: {
        value:
          'For a limited time, you can earn DOUBLE My Nintendo Gold Points on Mario Golf: Super Rush. That means you can earn 10% in Gold Points*—which you can then use toward your next eligible digital game or DLC. Golf with a Mushroom Kingdom twist! Hit the green…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    availability: ['Available now'],
    classindDescriptors: null,
    classindRating: 'E',
    collectionPriceRange: '$20 - $39.99',
    corePlatforms: ['Nintendo Switch'],
    createdAt: '2021-11-12T21:59:57.000Z',
    demoNsuid: '70030000013883',
    description:
      'For a limited time, you can earn DOUBLE My Nintendo Gold Points on Game Builder Garage. That means you can earn 10% in Gold Points*—which you can then use toward your next eligible digital game or DLC. Programming made fun with help from the minds at Nin…',
    editions: ['Digital'],
    esrbDescriptors: ['Mild Fantasy Violence'],
    esrbRating: 'E',
    exclusive: false,
    featuredProduct: true,
    franchises: [],
    genres: ['Education', 'Training'],
    nsoFeatures: ['Online Play', 'Save Data Cloud'],
    nsuid: '70010000041267',
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    platinumPoints: null,
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    playerCount: 'Single Player',
    price: {
      regPrice: 29.99,
      salePrice: null,
      finalPrice: 29.99,
    },
    priceRange: '$20 - $39.99',
    productImage: 'ncom/en_US/games/switch/g/game-builder-garage-switch/hero',
    releaseDateDisplay: null,
    sku: '7100041267',
    smecDescriptors: null,
    smecRating: null,
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    title: 'Game Builder Garage™',
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    topLevelFilters: ['Demo Available'],
    updatedAt: '2022-03-01T08:14:42.000Z',
    url: '/store/products/game-builder-garage-switch/',
    urlKey: 'game-builder-garage-switch',
    visibleInSearch: true,
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100041267',
    _highlightResult: {
      description: {
        value:
          'For a limited time, you can earn DOUBLE My Nintendo Gold Points on Game Builder Garage. That means you can earn 10% in Gold Points*—which you can then use toward your next eligible digital game or DLC. Programming made fun with help from the minds at Nin…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'DC Super Hero Girls™: Teen Power',
    topLevelFilters: [],
    nsoFeatures: ['Save Data Cloud'],
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: ['Action'],
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 59.99,
      salePrice: null,
      finalPrice: 59.99,
    },
    priceRange: '$40+',
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    collectionPriceRange: '$40 - $59.99',
    esrbRating: 'E10',
    esrbDescriptors: ['Cartoon Violence'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E10',
    classindDescriptors: ['Violence'],
    playerCount: 'Single Player',
    productImage: 'ncom/en_US/games/switch/d/dc-super-hero-girls-teen-power-switch/hero',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'Join the fight as Wonder Woman, Supergirl, and Batgirl from the animated series DC Super Hero Girls, and save Metropolis from the tinkering terror of Toyman! With the city in danger, even frenemies like Harley Quinn, Catwoman, and Star Sapphire will need…',
    sku: '7100038627',
    nsuid: '70010000038627',
    releaseDateDisplay: null,
    urlKey: 'dc-super-hero-girls-teen-power-switch',
    url: '/store/products/dc-super-hero-girls-teen-power-switch/',
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100038627',
    _highlightResult: {
      description: {
        value:
          'Join the fight as Wonder Woman, Supergirl, and Batgirl from the animated series DC Super Hero Girls, and save Metropolis from the tinkering terror of Toyman! With the city in danger, even frenemies like Harley Quinn, Catwoman, and Star Sapphire will need…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Hyrule Warriors: Age of Calamity + Hyrule Warriors: Age of Calamity Expansion Pass',
    topLevelFilters: ['Games with DLC'],
    nsoFeatures: null,
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: ['Action', 'Adventure', 'Fighting'],
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 79.98,
      salePrice: null,
      finalPrice: 79.98,
    },
    priceRange: '$40+',
    playModes: null,
    collectionPriceRange: '$60+',
    esrbRating: 'T',
    esrbDescriptors: ['Fantasy Violence'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E10',
    classindDescriptors: ['Violence'],
    playerCount: null,
    productImage:
      'ncom/en_US/dlc/switch-dlc/hyrule-warriors-age-of-calamity-dlc/rom-bundle/hyrule-warriors-age-of-calamity-plus-hyrule-warriors-age-of-calamity-expansion-pass/image',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'This bundle includes the Hyrule Warriors: Age of Calamity game for the Nintendo Switch™ system, along with the Expansion Pass DLC that offers two waves of downloadable content.  In Hyrule Warriors: Age of Calamity, you’ll see Hyrule 100 years before the …',
    sku: '7700012376',
    nsuid: '70070000012376',
    releaseDateDisplay: null,
    urlKey: 'hyrule-warriors-age-of-calamity-plus-hyrule-warriors-age-of-calamity-expansion-pass-switch',
    url: '/store/products/hyrule-warriors-age-of-calamity-plus-hyrule-warriors-age-of-calamity-expansion-pass-switch/',
    type: 'game',
    dlcType: 'ROM Bundle',
    hasDlc: true,
    objectID: '7700012376',
    _highlightResult: {
      description: {
        value:
          'This bundle includes the Hyrule Warriors: Age of Calamity game for the Nintendo Switch™ system, along with the Expansion Pass DLC that offers two waves of downloadable content.  In Hyrule Warriors: Age of Calamity, you’ll see Hyrule 100 years before the …',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Hyrule Warriors: Age of Calamity Expansion Pass',
    topLevelFilters: ['Games with DLC'],
    nsoFeatures: null,
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: ['Action', 'Adventure', 'Fighting'],
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 19.99,
      salePrice: null,
      finalPrice: 19.99,
    },
    priceRange: '$10 - $19.99',
    playModes: null,
    collectionPriceRange: '$10 - $19.99',
    esrbRating: 'T',
    esrbDescriptors: ['Fantasy Violence'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E10',
    classindDescriptors: ['Violence'],
    playerCount: null,
    productImage:
      'ncom/en_US/dlc/switch-dlc/hyrule-warriors-age-of-calamity-dlc/bundles/hyrule-warriors-age-of-calamity-expansion-pass/image',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'Two waves of downloadable content are coming in the Hyrule Warriors: Age of Calamity Expansion Pass DLC. Newly added characters, stages, and more are all on their way! Purchase this expansion pass to get both waves of DLC as they are released. As a purch…',
    sku: '7700011785',
    nsuid: '70070000011785',
    releaseDateDisplay: null,
    urlKey: 'hyrule-warriors-age-of-calamity-expansion-pass-70070000011785-switch',
    url: '/store/products/hyrule-warriors-age-of-calamity-expansion-pass-70070000011785-switch/',
    type: 'game',
    dlcType: 'Bundle',
    hasDlc: true,
    objectID: '7700011785',
    _highlightResult: {
      description: {
        value:
          'Two waves of downloadable content are coming in the Hyrule Warriors: Age of Calamity Expansion Pass DLC. Newly added characters, stages, and more are all on their way! Purchase this expansion pass to get both waves of DLC as they are released. As a purch…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Miitopia™',
    topLevelFilters: ['Demo Available'],
    nsoFeatures: ['Online Play', 'Save Data Cloud'],
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: ['Adventure', 'Role-Playing'],
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: '70030000013605',
    platinumPoints: null,
    price: {
      regPrice: 49.99,
      salePrice: null,
      finalPrice: 49.99,
    },
    priceRange: '$40+',
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    collectionPriceRange: '$40 - $59.99',
    esrbRating: 'E',
    esrbDescriptors: ['Mild Cartoon Violence', 'Mild Language', 'Crude Humor'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E',
    classindDescriptors: ['Violence'],
    playerCount: 'Single Player',
    productImage: 'ncom/en_US/games/switch/m/miitopia-switch/hero',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'Cast your friends, family or anyone you choose in a comedy-filled adventure to bring down the face-stealing Dark Lord. Create and customize Mii™ characters of anyone you like and assign them roles in the fantasy adventure of a lifetime. With expanded cus…',
    sku: '7100038617',
    nsuid: '70010000038617',
    releaseDateDisplay: null,
    urlKey: 'miitopia-switch',
    url: '/store/products/miitopia-switch/',
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100038617',
    _highlightResult: {
      description: {
        value:
          'Cast your friends, family or anyone you choose in a comedy-filled adventure to bring down the face-stealing Dark Lord. Create and customize Mii™ characters of anyone you like and assign them roles in the fantasy adventure of a lifetime. With expanded cus…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Famicom Detective Club™: The Missing Heir',
    topLevelFilters: [],
    nsoFeatures: ['Save Data Cloud'],
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: ['Adventure', 'Simulation'],
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 34.99,
      salePrice: null,
      finalPrice: 34.99,
    },
    priceRange: '$20 - $39.99',
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    collectionPriceRange: '$20 - $39.99',
    esrbRating: 'T',
    esrbDescriptors: ['Blood', 'Violence', 'Language', 'Use of Tobacco'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E12',
    classindDescriptors: ['Violence', 'Legal Drugs', 'Inappropriate Language'],
    playerCount: 'Single Player',
    productImage: 'ncom/en_US/games/switch/f/famicom-detective-club-the-missing-heir-switch/hero',
    softwareDeveloper: null,
    softwarePublisher: 'Nintendo',
    description:
      'Hunt for clues, talk to suspects, and explore the Japanese countryside after tragedy strikes the wealthy Ayashiro family. Filled with suspense, this tale follows an amnesia-stricken detective trying to unravel his own past amidst the horrors of a harrowi…',
    sku: '7100039215',
    nsuid: '70010000039215',
    releaseDateDisplay: null,
    urlKey: 'famicom-detective-club-the-missing-heir-switch',
    url: '/store/products/famicom-detective-club-the-missing-heir-switch/',
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100039215',
    _highlightResult: {
      description: {
        value:
          'Hunt for clues, talk to suspects, and explore the Japanese countryside after tragedy strikes the wealthy Ayashiro family. Filled with suspense, this tale follows an amnesia-stricken detective trying to unravel his own past amidst the horrors of a harrowi…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
  {
    title: 'Famicom Detective Club™: The Girl Who Stands Behind',
    topLevelFilters: [],
    nsoFeatures: ['Save Data Cloud'],
    platform: 'Nintendo Switch',
    platformCode: 'NINTENDO_SWITCH',
    corePlatforms: ['Nintendo Switch'],
    availability: ['Available now'],
    genres: ['Adventure', 'Simulation'],
    editions: ['Digital'],
    featuredProduct: true,
    franchises: [],
    topLevelCategory: 'Games',
    topLevelCategoryCode: 'GAMES',
    visibleInSearch: true,
    exclusive: false,
    demoNsuid: null,
    platinumPoints: null,
    price: {
      regPrice: 34.99,
      salePrice: null,
      finalPrice: 34.99,
    },
    priceRange: '$20 - $39.99',
    playModes: ['TV mode', 'Tabletop mode', 'Handheld mode'],
    collectionPriceRange: '$20 - $39.99',
    esrbRating: 'T',
    esrbDescriptors: ['Blood', 'Violence', 'Suggestive Themes', 'Use of Alcohol and Tobacco'],
    smecRating: null,
    smecDescriptors: null,
    classindRating: 'E12',
    classindDescriptors: ['Violence', 'Sexual Content', 'Legal Drugs'],
    playerCount: 'Single Player',
    productImage: 'ncom/en_US/games/switch/f/famicom-detective-club-the-girl-who-stands-behind-switch/hero',
    softwareDeveloper: ' ',
    softwarePublisher: 'Nintendo',
    description:
      'Interrogate suspects and hunt for clues to piece together chilling conundrums plaguing a high school in Japan. Suspense (and a little bit of horror) ensues as you try to free students from their nightmare. Play at home, on the go, or in your favorite rea…',
    sku: '7100039214',
    nsuid: '70010000039214',
    releaseDateDisplay: null,
    urlKey: 'famicom-detective-club-the-girl-who-stands-behind-switch',
    url: '/store/products/famicom-detective-club-the-girl-who-stands-behind-switch/',
    type: 'game',
    dlcType: null,
    hasDlc: false,
    objectID: '7100039214',
    _highlightResult: {
      description: {
        value:
          'Interrogate suspects and hunt for clues to piece together chilling conundrums plaguing a high school in Japan. Suspense (and a little bit of horror) ensues as you try to free students from their nightmare. Play at home, on the go, or in your favorite rea…',
        matchLevel: 'none',
        matchedWords: [],
      },
    },
  },
];
